/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TransactionHash: typeof import('./src/components/TransactionHash.vue')['default']
    TransactionModal: typeof import('./src/components/TransactionModal.vue')['default']
  }
}
